name: money_mangement
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.2.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  get: ^4.6.5
  google_sign_in: ^6.1.2
  intl: ^0.18.1
  permission_handler: ^10.3.0
  social_login_buttons: ^1.0.7
  timezone: ^0.9.2
  workmanager: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
